---
- hosts: node1.snetesa.club
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: write the index.html
      copy:
        dest: /var/www/html/index.html
        content: Welcome to my web server!
    - name: start apache server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: open ports in firewall
      firewalld:
        state: enabled
        service: "{{ item }}"
        permanent: yes
        zone: public
        immediate: yes
      loop:
        - http
        - https
    - name: bind network interface to public zone
      firewalld:
        state: enabled
        permanent: yes
        interface: "{{ ansible_default_ipv4.interface }}"
        zone: public
        immediate: yes