---
- hosts: node1.snetesa.club
  become: yes
  tasks:
    - name: disable Network Manager
      service:
        name: NetworkManager
        enabled: no
        state: stopped
    - name: tune grub config 
      lineinfile:
          path: /etc/default/grub
          backrefs: yes
          regexp: '(^GRUB_CMDLINE_LINUX=(?!.* {{item}})\".*)(\"$)'
          backup: yes
          line: '\1 {{item}}\2'
      loop:
        - net.ifnames=0
        - biosdevname=0
    - name: build grub config
      command:
        cmd: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg