---
- hosts: node1.snetesa.club
  become: yes
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: write the index.html
      copy:
        dest: /var/www/html/index.html
        content: Welcome to my web server
    - name: start apache server
      service:
        name: httpd
        state: started
